#!/usr/bin/env python3
"""Independent local audit of formal IEEE revision Step 5 artifacts."""

from __future__ import annotations

import csv
import hashlib
import json
import math
from collections import defaultdict
from pathlib import Path
from typing import Any, Iterable, Mapping, Sequence

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
SERVER = ROOT / "server_results/ieee_revision/step5_s05"
OUT = ROOT / "outputs/ieee_revision/step5_s05"
LABELS = ("neutral", "surprise", "fear", "sadness", "joy", "disgust", "anger")
EXPERIMENTS = ("no_S05", "all_S05", "filtered_S05")
SEEDS = tuple(range(42, 50))
SCENARIOS = ("full", "missing_video", "random_missing")
METRICS = ("accuracy", "weighted_f1", "macro_f1", "f1_fds")
CONTRASTS = (
    ("all_vs_none", "no_S05", "all_S05"),
    ("filtered_vs_none", "no_S05", "filtered_S05"),
    ("filtered_vs_all", "all_S05", "filtered_S05"),
)


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def read_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8-sig", newline="") as handle:
        return list(csv.DictReader(handle))


def write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def write_latex_macros(payload: Mapping[str, Any]) -> Path:
    """Generate manuscript numbers only from independently recomputed artifacts."""
    output = ROOT / "paper/submission/source/generated/s05_filtering_numbers.tex"
    differences = payload["matched_full_test_differences"]
    bundle = payload["filtered_bundle"]

    def delta(contrast: str, metric: str) -> str:
        return f"{differences[contrast][metric]['mean_delta']:+.4f}"

    def signs(contrast: str, metric: str) -> str:
        row = differences[contrast][metric]
        return f"{row['positive_seeds']}/{row['negative_seeds']}"

    macros = {
        "SFiveAuditRows": "120",
        "SFiveFinalRows": str(bundle["rows_before"]),
        "SFiveFinalAuditOverlap": "16",
        "SFiveDirectFailures": str(bundle["rows_excluded"]),
        "SFiveFilteredRows": str(bundle["rows_after"]),
        "SFiveFinalUnauditedRows": "592",
        "SFiveAllAccDeltaEight": delta("all_vs_none", "accuracy"),
        "SFiveAllWeightedDeltaEight": delta("all_vs_none", "weighted_f1"),
        "SFiveAllMacroDeltaEight": delta("all_vs_none", "macro_f1"),
        "SFiveAllFDSDeltaEight": delta("all_vs_none", "f1_fds"),
        "SFiveAllMacroSignsEight": signs("all_vs_none", "macro_f1"),
        "SFiveAllFDSSignsEight": signs("all_vs_none", "f1_fds"),
        "SFiveFilterAccVsAllEight": delta("filtered_vs_all", "accuracy"),
        "SFiveFilterWeightedVsAllEight": delta("filtered_vs_all", "weighted_f1"),
        "SFiveFilterMacroVsAllEight": delta("filtered_vs_all", "macro_f1"),
        "SFiveFilterFDSVsAllEight": delta("filtered_vs_all", "f1_fds"),
        "SFiveFilterMacroSignsEight": signs("filtered_vs_all", "macro_f1"),
        "SFiveFilterFDSSignsEight": signs("filtered_vs_all", "f1_fds"),
    }
    lines = [
        "% AUTO-GENERATED by scripts/audit_revision_step5_s05.py.",
        "% Source: independently verified Step 5 server artifacts; do not edit manually.",
    ]
    lines.extend(f"\\newcommand{{\\{name}}}{{{value}}}" for name, value in macros.items())
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return output


def mapped_step5(path: str) -> Path:
    rel = Path(path).relative_to("outputs/ieee_revision/step5_s05")
    return SERVER / rel


def metric_from_confusion(confusion: np.ndarray) -> tuple[dict[str, float], list[dict[str, Any]]]:
    support = confusion.sum(axis=1)
    predicted = confusion.sum(axis=0)
    tp = np.diag(confusion)
    precision = np.divide(tp, predicted, out=np.zeros(7, dtype=float), where=predicted != 0)
    recall = np.divide(tp, support, out=np.zeros(7, dtype=float), where=support != 0)
    denom = predicted + support
    f1 = np.divide(2 * tp, denom, out=np.zeros(7, dtype=float), where=denom != 0)
    total = int(support.sum())
    metrics = {
        "accuracy": float(tp.sum() / total),
        "weighted_f1": float(np.dot(f1, support) / total),
        "macro_f1": float(f1.mean()),
        "f1_fds": float(f1[[2, 5, 3]].mean()),
    }
    classes = [{
        "label": LABELS[i], "precision": float(precision[i]), "recall": float(recall[i]),
        "f1": float(f1[i]), "support": int(support[i]),
    } for i in range(7)]
    return metrics, classes


def verify_manifest(errors: list[str]) -> dict[str, Any]:
    manifest = read_json(SERVER / "final_manifest.json")
    listed = set()
    for row in manifest["files"]:
        path = mapped_step5(row["path"])
        listed.add(str(path.relative_to(SERVER)))
        if not path.is_file():
            errors.append(f"manifest missing: {path}")
            continue
        if path.stat().st_size != int(row["bytes"]):
            errors.append(f"manifest size mismatch: {path}")
        if sha256(path) != row["sha256"]:
            errors.append(f"manifest hash mismatch: {path}")
    actual = {
        str(path.relative_to(SERVER)) for path in SERVER.rglob("*")
        if path.is_file() and path.name != "final_manifest.json"
        and not str(path.relative_to(SERVER)).startswith("slurm_logs/")
    }
    if actual != listed:
        errors.append(f"manifest inventory mismatch: unlisted={sorted(actual-listed)} missing={sorted(listed-actual)}")
    return {
        "entries": len(manifest["files"]), "entries_verified": len(manifest["files"]) - sum("manifest " in e for e in errors),
        "unlisted_formal_files": sorted(actual - listed), "missing_listed_files": sorted(listed - actual),
        "final_manifest_sha256": sha256(SERVER / "final_manifest.json"),
    }


def verify_bundle(errors: list[str]) -> dict[str, Any]:
    original = np.load(ROOT / "server_results/phase2_minority_augmentation/bundles/S05.npz", allow_pickle=False)
    filtered = np.load(SERVER / "filtered_S05_audited_failures_v1.npz", allow_pickle=False)
    rule = read_json(SERVER / "filter_manifest.json")
    positions = {int(row["s05_row_position_zero_based"]) for row in rule["excluded"]}
    keep = np.asarray([i not in positions for i in range(608)])
    if not np.array_equal(filtered["source_indices"], original["source_indices"][keep]):
        errors.append("filtered S05 source indices do not equal exact five-row deletion")
    if not np.array_equal(filtered["text_features"], original["text_features"][keep]):
        errors.append("filtered S05 text features do not equal exact five-row deletion")
    if filtered["text_features"].shape != (603, 3584) or filtered["text_features"].dtype != np.float32:
        errors.append("filtered S05 shape/dtype mismatch")
    if not np.isfinite(filtered["text_features"]).all():
        errors.append("filtered S05 contains non-finite values")
    bundle_manifest = read_json(SERVER / "filtered_bundle_manifest.json")
    if sha256(SERVER / "filtered_S05_audited_failures_v1.npz") != bundle_manifest["sha256"]:
        errors.append("filtered bundle manifest hash mismatch")
    return {
        "rows_before": 608, "rows_excluded": len(positions), "rows_after": int(len(filtered["source_indices"])),
        "shape": list(filtered["text_features"].shape), "dtype": str(filtered["text_features"].dtype),
        "finite_fraction": float(np.isfinite(filtered["text_features"]).mean()),
        "exact_array_deletion_verified": not any("filtered S05" in e for e in errors),
        "bundle_sha256": sha256(SERVER / "filtered_S05_audited_failures_v1.npz"),
    }


def verify_runs(errors: list[str]) -> dict[str, Any]:
    rows = read_csv(SERVER / "checkpoint_index.csv")
    if {(row["experiment"], int(row["seed"])) for row in rows} != {("filtered_S05", seed) for seed in SEEDS}:
        errors.append("checkpoint experiment/seed set mismatch")
    best_epoch_ok = True
    config_ok = True
    train_seconds = []
    for row in rows:
        seed = int(row["seed"])
        for field, hash_field in (("config", "config_sha256"), ("checkpoint", "checkpoint_sha256"), ("prototype", "prototype_sha256")):
            path = mapped_step5(row[field])
            if not path.is_file() or sha256(path) != row[hash_field]:
                errors.append(f"{field} hash mismatch seed {seed}")
        log_path = mapped_step5(row["log"])
        if not log_path.is_file():
            errors.append(f"missing training log seed {seed}")
        config_path = mapped_step5(row["config"])
        cfg = read_json(config_path)
        expected = {
            "seed": seed, "epochs": 20, "batch_size": 64, "hidden_dim": 128, "num_heads": 4,
            "dropout": 0.3, "lr": 0.001, "weight_decay": 0.0001, "patience": 5,
            "loss_type": "ce", "class_weight_mode": "none", "structure_mode": "speaker_distance",
            "context_len": 5, "context_max_distance": 20, "fusion": "tv_disagreement",
            "train_video_mask_prob": 0.5, "speaker_memory_mode": "prototype",
        }
        if any(cfg.get(key) != value for key, value in expected.items()):
            config_ok = False; errors.append(f"frozen training config mismatch seed {seed}")
        if not str(cfg.get("augmentation_bundle", "")).endswith("outputs/ieee_revision/step5_s05/filtered_S05_audited_failures_v1.npz"):
            config_ok = False; errors.append(f"filtered bundle config mismatch seed {seed}")
        history = read_json(config_path.parent / "training_history.json")
        val = np.asarray(history["val_f1"], dtype=float)
        expected_epoch = int(np.argmax(val)) + 1
        if int(cfg["results"]["best_epoch"]) != expected_epoch or not math.isclose(float(cfg["results"]["best_val_f1"]), float(val.max()), abs_tol=1e-12):
            best_epoch_ok = False; errors.append(f"dev weighted-F1 checkpoint selection mismatch seed {seed}")
        train_seconds.append(float(row["train_seconds"]))
    values = np.asarray(train_seconds)
    return {
        "checkpoint_count": len(rows), "checkpoint_hashes_verified": len(rows),
        "config_contract_verified": config_ok, "dev_weighted_f1_selection_verified": best_epoch_ok,
        "prototype_hashes_verified": len(rows), "training_seconds_mean": float(values.mean()),
        "training_seconds_sample_sd": float(values.std(ddof=1)), "training_seconds_total": float(values.sum()),
    }


def load_saved_metrics(split: str) -> dict[tuple[str, int, str], dict[str, float]]:
    output = {}
    for row in read_csv(SERVER / f"{split}_metrics.csv"):
        output[(row["experiment"], int(row["seed"]), row["scenario"])] = {metric: float(row[metric]) for metric in METRICS}
    return output


def load_saved_classes(split: str) -> dict[tuple[str, int, str, str], dict[str, float]]:
    output = {}
    for row in read_csv(SERVER / f"{split}_per_class.csv"):
        output[(row["experiment"], int(row["seed"]), row["scenario"], row["label"])] = {
            "precision": float(row["precision"]), "recall": float(row["recall"]),
            "f1": float(row["f1"]), "support": int(row["support"]),
        }
    return output


def verify_predictions(split: str, errors: list[str]) -> dict[str, Any]:
    feature = ROOT / "datasets/MELD/features_v2"
    gold_ref = np.load(feature / f"{split}_labels.npy", allow_pickle=False)
    did_ref = np.load(feature / f"{split}_dialogue_ids.npy", allow_pickle=False)
    uid_ref = np.load(feature / f"{split}_utterance_ids.npy", allow_pickle=False)
    speaker_ref = np.load(feature / f"{split}_speakers.npy", allow_pickle=True)
    expected_rows = len(gold_ref)
    confusion: dict[tuple[str, int, str], np.ndarray] = defaultdict(lambda: np.zeros((7, 7), dtype=np.int64))
    seen: dict[tuple[str, int, str], set[int]] = defaultdict(set)
    probability_failures = 0
    identity_failures = 0
    argmax_failures = 0
    total = 0
    with (SERVER / f"{split}_predictions.csv").open(encoding="utf-8", newline="") as handle:
        for row in csv.DictReader(handle):
            total += 1
            key = (row["experiment"], int(row["seed"]), row["scenario"])
            idx = int(row["sample_index"]); gold = int(row["gold"]); pred = int(row["prediction"])
            if idx < 0 or idx >= expected_rows or idx in seen[key]:
                identity_failures += 1; continue
            seen[key].add(idx)
            if gold != int(gold_ref[idx]) or str(row["dialogue_id"]) != str(did_ref[idx]) or str(row["utterance_id"]) != str(uid_ref[idx]) or str(row["speaker"]) != str(speaker_ref[idx]):
                identity_failures += 1
            probs = np.asarray([float(row[f"prob_{label}"]) for label in LABELS])
            if not np.isfinite(probs).all() or not np.isclose(probs.sum(), 1.0, atol=2e-6):
                probability_failures += 1
            if int(probs.argmax()) != pred:
                argmax_failures += 1
            confusion[key][gold, pred] += 1
    expected_keys = {(experiment, seed, scenario) for experiment in EXPERIMENTS for seed in SEEDS for scenario in SCENARIOS}
    if set(confusion) != expected_keys:
        errors.append(f"{split} prediction group set mismatch")
    if any(len(seen[key]) != expected_rows for key in expected_keys):
        errors.append(f"{split} prediction group row/identity count mismatch")
    if identity_failures or probability_failures or argmax_failures:
        errors.append(f"{split} prediction validation failures identity={identity_failures} probability={probability_failures} argmax={argmax_failures}")

    saved_metrics = load_saved_metrics(split)
    saved_classes = load_saved_classes(split)
    metric_max_error = 0.0
    class_max_error = 0.0
    recomputed = {}
    for key in expected_keys:
        metrics, classes = metric_from_confusion(confusion[key])
        recomputed[key] = metrics
        for metric in METRICS:
            metric_max_error = max(metric_max_error, abs(metrics[metric] - saved_metrics[key][metric]))
        for row in classes:
            saved = saved_classes[(*key, row["label"])]
            for field in ("precision", "recall", "f1", "support"):
                class_max_error = max(class_max_error, abs(float(row[field]) - float(saved[field])))
    if metric_max_error > 1e-12 or class_max_error > 1e-12:
        errors.append(f"{split} saved metric recomputation mismatch")
    return {
        "rows": total, "groups": len(confusion), "rows_per_group": expected_rows,
        "identity_failures": identity_failures, "probability_failures": probability_failures,
        "argmax_failures": argmax_failures, "metric_max_abs_error": metric_max_error,
        "per_class_max_abs_error": class_max_error,
        "recomputed": recomputed,
    }


def verify_imported_step2(split: str, errors: list[str]) -> dict[str, Any]:
    step2 = ROOT / "server_results/ieee_revision/step2_seeds" / f"{split}_predictions.csv"
    expected = []
    with step2.open(encoding="utf-8", newline="") as handle:
        for row in csv.DictReader(handle):
            if row["experiment"] in ("A6", "A7"):
                row = dict(row); row["experiment"] = "no_S05" if row["experiment"] == "A6" else "all_S05"
                expected.append(row)
    actual = []
    with (SERVER / f"{split}_predictions.csv").open(encoding="utf-8", newline="") as handle:
        for row in csv.DictReader(handle):
            if row["experiment"] in ("no_S05", "all_S05"):
                actual.append(row)
    if expected != actual:
        errors.append(f"{split} imported Step 2 predictions differ after experiment relabeling")
    return {"rows": len(actual), "exact_row_equality_after_relabeling": expected == actual}


def verify_summaries(recomputed: Mapping[tuple[str, int, str], Mapping[str, float]], split: str, errors: list[str]) -> None:
    summary = {(row["experiment"], row["split"], row["scenario"]): row for row in read_csv(SERVER / "summary_metrics.csv")}
    for experiment in EXPERIMENTS:
        for scenario in SCENARIOS:
            row = summary[(experiment, split, scenario)]
            for metric in METRICS:
                values = np.asarray([recomputed[(experiment, seed, scenario)][metric] for seed in SEEDS])
                checks = {
                    "mean": values.mean(), "sd": values.std(ddof=1), "median": np.median(values),
                    "min": values.min(), "max": values.max(),
                }
                for stat, value in checks.items():
                    if not math.isclose(float(row[f"{metric}_{stat}"]), float(value), abs_tol=1e-12):
                        errors.append(f"summary mismatch {experiment}/{split}/{scenario}/{metric}/{stat}")


def verify_differences(dev: Mapping[tuple[str, int, str], Mapping[str, float]], test: Mapping[tuple[str, int, str], Mapping[str, float]], errors: list[str]) -> dict[str, Any]:
    rows = read_csv(SERVER / "per_seed_differences.csv")
    saved = {(row["contrast"], row["split"], row["scenario"], int(row["seed"])): row for row in rows}
    output = {}
    for name, control, treatment in CONTRASTS:
        output[name] = {}
        for split, metrics in (("dev", dev), ("test", test)):
            for scenario in SCENARIOS:
                per_seed = {metric: [] for metric in METRICS}
                for seed in SEEDS:
                    row = saved[(name, split, scenario, seed)]
                    for metric in METRICS:
                        delta = metrics[(treatment, seed, scenario)][metric] - metrics[(control, seed, scenario)][metric]
                        if not math.isclose(float(row[f"delta_{metric}"]), delta, abs_tol=1e-12):
                            errors.append(f"difference mismatch {name}/{split}/{scenario}/{seed}/{metric}")
                        per_seed[metric].append(delta)
                if split == "test" and scenario == "full":
                    output[name] = {
                        metric: {
                            "mean_delta": float(np.mean(values)), "sample_sd": float(np.std(values, ddof=1)),
                            "positive_seeds": int(np.sum(np.asarray(values) > 0)),
                            "negative_seeds": int(np.sum(np.asarray(values) < 0)),
                            "zero_seeds": int(np.sum(np.asarray(values) == 0)),
                            "per_seed": {str(seed): float(value) for seed, value in zip(SEEDS, values)},
                        } for metric, values in per_seed.items()
                    }
    return output


def full_test_summary(test: Mapping[tuple[str, int, str], Mapping[str, float]]) -> dict[str, Any]:
    classes = load_saved_classes("test")
    output = {}
    for experiment in EXPERIMENTS:
        item = {}
        for metric in METRICS:
            values = np.asarray([test[(experiment, seed, "full")][metric] for seed in SEEDS])
            item[metric] = {"mean": float(values.mean()), "sample_sd": float(values.std(ddof=1))}
        item["minority_class_f1"] = {}
        for label in ("fear", "sadness", "disgust"):
            values = np.asarray([classes[(experiment, seed, "full", label)]["f1"] for seed in SEEDS])
            item["minority_class_f1"][label] = {"mean": float(values.mean()), "sample_sd": float(values.std(ddof=1))}
        output[experiment] = item
    return output


def verify_slurm(errors: list[str]) -> dict[str, Any]:
    evidence = {
        "failed_dev_3137931": ("dev_sacct_3137931.txt", "FAILED", "1:0"),
        "formal_dev_3137944": ("dev_sacct_3137944.txt", "COMPLETED", "0:0"),
        "formal_test_3140704": ("test_sacct_3140704.txt", "COMPLETED", "0:0"),
    }
    result = {}
    for name, (filename, state, exit_code) in evidence.items():
        text = (SERVER / "slurm" / filename).read_text(encoding="utf-8")
        ok = state in text and exit_code in text
        if not ok: errors.append(f"Slurm evidence mismatch: {name}")
        result[name] = {"state": state, "exit_code": exit_code, "verified": ok}
    for job in ("3137931", "3137944", "3140704"):
        out = SERVER / "slurm" / (f"rev_s5_dev_{job}.out" if job != "3140704" else f"rev_s5_test_{job}.out")
        err = out.with_suffix(".err")
        if not out.is_file() or not err.is_file(): errors.append(f"missing Slurm logs {job}")
        if job in ("3137944", "3140704") and err.stat().st_size != 0: errors.append(f"formal Slurm stderr nonempty {job}")
    dev_runtime = (SERVER / "runtime/dev_machine_3137944.log").read_text(encoding="utf-8")
    test_runtime = (SERVER / "runtime/test_machine_3140704.log").read_text(encoding="utf-8")
    for name, text in (("dev", dev_runtime), ("test", test_runtime)):
        for marker in ("torch 2.5.1+cu121", "cuda_available True", "Tesla V100-SXM2-16GB", "FORMAL_COMMAND"):
            if marker not in text: errors.append(f"missing {name} runtime marker: {marker}")
    result["runtime_gpu_evidence_verified"] = not any("runtime marker" in e for e in errors)
    snapshot = SERVER / "slurm/test_squeue_submit_3140704.txt"
    result["test_submission_snapshot_bytes"] = snapshot.stat().st_size
    result["test_submission_snapshot_limitation"] = "server snapshot was truncated by a later tee; job ID, pasted terminal record and sacct remain" if snapshot.stat().st_size == 0 else None
    return result


def main() -> None:
    errors: list[str] = []
    manifest = verify_manifest(errors)
    bundle = verify_bundle(errors)
    runs = verify_runs(errors)
    dev_result = verify_predictions("dev", errors)
    test_result = verify_predictions("test", errors)
    verify_summaries(dev_result["recomputed"], "dev", errors)
    verify_summaries(test_result["recomputed"], "test", errors)
    imported = {
        "dev": verify_imported_step2("dev", errors),
        "test": verify_imported_step2("test", errors),
    }
    differences = verify_differences(dev_result["recomputed"], test_result["recomputed"], errors)
    slurm = verify_slurm(errors)
    result_gate = read_json(SERVER / "result_gate.json")
    if result_gate.get("decision") != "STEP5_FILTER_RESULTS_READY_FOR_LOCAL_AUDIT" or result_gate.get("test_used_for_selection") is not False or result_gate.get("new_test_inference_passes_per_checkpoint_scenario") != 1:
        errors.append("result gate policy mismatch")

    dev_result.pop("recomputed")
    test_recomputed = test_result.pop("recomputed")
    payload = {
        "step": 5, "status": "PASS" if not errors else "FAIL", "errors": errors,
        "manifest": manifest, "filtered_bundle": bundle, "runs": runs,
        "predictions": {"dev": dev_result, "test": test_result},
        "step2_import": imported, "slurm": slurm,
        "full_test_summary": full_test_summary(test_recomputed),
        "matched_full_test_differences": differences,
        "interpretation": {
            "filtering_result": "The exact five-row audited-failure exclusion does not show a consistent advantage over all-S05 across the eight frozen seeds.",
            "noise_result": "The experiment does not establish that noise was removed: 592 retained final-S05 rows remain unaudited, and the 120-row audit was not sampled directly from final S05.",
            "s05_result": "All-S05 versus no-S05 remains artifact-specific: balanced-metric mean deltas are positive, but every metric has at least one non-positive or negative seed and aggregate Accuracy is lower.",
            "causal_boundary": "Neither augmentation nor exact filtering isolates label correctness from copied-video/replaced-text cross-modal inconsistency.",
        },
        "source_hashes": {
            "server_final_manifest": sha256(SERVER / "final_manifest.json"),
            "server_result_gate": sha256(SERVER / "result_gate.json"),
            "server_checkpoint_index": sha256(SERVER / "checkpoint_index.csv"),
            "server_test_predictions": sha256(SERVER / "test_predictions.csv"),
            "server_per_seed_differences": sha256(SERVER / "per_seed_differences.csv"),
        },
    }
    write_json(OUT / "local_audit.json", payload)
    latex_macro_path = write_latex_macros(payload)

    f = payload["full_test_summary"]
    d = payload["matched_full_test_differences"]
    lines = [
        "# Step 5 formal S05 filtering results", "",
        f"Local independent audit: **{payload['status']}**. The final manifest contains {manifest['entries']} verified entries; dev/test prediction rows are {dev_result['rows']:,}/{test_result['rows']:,} with zero identity, probability, argmax, metric, or per-class mismatches.", "",
        "## Full-input test results across seeds 42--49", "",
        "| Condition | Accuracy | Weighted F1 | Macro F1 | F1_FDS |", "|---|---:|---:|---:|---:|",
    ]
    for experiment in EXPERIMENTS:
        row = f[experiment]
        lines.append("| {} | {} | {} | {} | {} |".format(experiment, *[
            f"{row[m]['mean']:.4f} ± {row[m]['sample_sd']:.4f}" for m in METRICS
        ]))
    lines += ["", "## Full-input matched mean differences", "", "| Contrast | Accuracy | Weighted F1 | Macro F1 | F1_FDS |", "|---|---:|---:|---:|---:|"]
    for contrast, _, _ in CONTRASTS:
        lines.append("| {} | {} | {} | {} | {} |".format(contrast, *[
            f"{d[contrast][m]['mean_delta']:+.4f} ({d[contrast][m]['positive_seeds']}/{d[contrast][m]['negative_seeds']} +/− seeds)" for m in METRICS
        ]))
    lines += [
        "", "Filtering five directly audited failures does not consistently outperform all-S05: its full-test mean differences are near zero for Accuracy/Weighted F1 and negative for Macro F1/F1_FDS, with mixed signs across seeds. This is a completed negative filtering result, not evidence that the remaining augmentation labels are clean.", "",
        "The candidate-audit sadness meaning-preservation value remains 28/40 = 0.70. It is a quality-risk indicator for the audited stratum, not the 608-row S05 noise rate. The historical +0.0609 F1_FDS is a three-seed, utterance-bootstrap-conditioned value for the current S05 artifact; the eight-seed all-S05 minus no-S05 mean is reported separately. Neither supports universal augmentation correctness.", "",
        "The failed infrastructure job 3137931 is retained. Formal dev 3137944 and test 3140704 completed with ExitCode 0:0. The test submission `squeue` snapshot file is zero bytes because a later `tee` truncated it; no reconstruction is made.", "",
    ]
    (OUT / "results_report.md").write_text("\n".join(lines), encoding="utf-8")
    print(json.dumps({"status": payload["status"], "errors": errors, "manifest_entries": manifest["entries"], "dev_rows": dev_result["rows"], "test_rows": test_result["rows"], "latex_macros": str(latex_macro_path.relative_to(ROOT))}, indent=2))


if __name__ == "__main__":
    main()
