#!/usr/bin/env python3
"""Generate Step 7 protocol artifacts and the manuscript Algorithm 1 source."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "outputs/ieee_revision/step7_protocol"
PAPER_COPY = ROOT / "paper/submission/source/generated/frozen_evidence_factorial_audit_algorithm.tex"


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def write_if_changed(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == text:
        return
    path.write_text(text, encoding="utf-8")


def write_json(path: Path, payload: Any) -> None:
    write_if_changed(path, json.dumps(payload, ensure_ascii=False, indent=2) + "\n")


def algorithm_text() -> str:
    return r"""% AUTO-GENERATED by scripts/build_revision_step7_protocol.py.
% Canonical revision artifact: outputs/ieee_revision/step7_protocol/algorithm_source.tex.
\begin{algorithm*}[!t]
\caption{Frozen-Evidence Factorial Audit Protocol}
\label{alg:frozen-evidence-audit}
\begin{algorithmic}[1]
\Require Dataset and immutable IDs $D$; feature contract $F$; inherited backbone $B$; split $S=(S_{tr},S_{dev},S_{te})$; task metrics $M$
\Ensure Claim ledger $L$ and hashed evidence package $A$
\State Define experimental object $O=\{D,F,\text{prompt},\text{pooling},B,S,M\}$; changing any member creates a new object.
\State Separate the \emph{inherited backbone}, each \emph{audited factor}, and each train-only \emph{training intervention}.
\State Predeclare factors, matched contrasts $C$, seeds $R$, dev selection metric $m_{dev}$, test policy, and claim gates $G$.
\ForAll{$(c,r)\in C\times R$}
  \State Train with $S_{tr}$ and select only with $S_{dev}$ using $m_{dev}$; freeze the selected checkpoint.
  \State If the dev/integrity gate passes, execute the frozen $S_{te}$ inference exactly as preregistered; never reselect from test.
\EndFor
\State Join treatment/control predictions using immutable sample, dialogue, utterance, speaker, and gold-label IDs.
\State Report task metrics, robustness, paired-utterance uncertainty, and training-seed variability as separate evidence layers.
\State Hash features, configurations, checkpoints, and predictions; archive seeds, commands, logs, environment, and hardware records.
\State Assign each claim to \textbf{Supported}, \textbf{Restricted}, \textbf{Rejected}, \textbf{Untested}, or execution \textbf{No-Go}; do not upgrade wording beyond its gate.
\end{algorithmic}
\end{algorithm*}
"""


def migration_text() -> str:
    return """# Step 7 migration boundary

## Transferable protocol

The reusable object is the audit sequence: define the experimental object; separate inherited and varied components; preregister factors, matched contrasts, seeds, development selection, and claim gates; freeze before test; join paired predictions by immutable IDs; separate task, robustness, utterance, and training-seed evidence; hash artifacts and environment; and apply the claim ledger.

## Dataset and training changes that require a new experimental object

- **IEMOCAP:** use session-independent and speaker-independent folds. MELD speaker strings, dialogue graph, split counts, class weights, thresholds, and numerical gates do not transfer.
- **CMU-MOSEI:** redefine the task unit, labels, modalities, alignment, and sequence-length handling. The protocol steps transfer, but no MELD score, threshold, class-specific gate, or effect size transfers.
- **Trimodal tasks:** add audio availability as an explicit object field and preregister audio main effects and relevant interaction factors, including missing-audio conditions. Text-video conclusions do not establish audio interactions.
- **End-to-end training:** replace the frozen-cache contract with extractor/model revision, preprocessing, decoding, optimizer, compute, nondeterminism, checkpoint, and intermediate-artifact contracts. Compute and randomness budgets must be redefined.

## Claim boundary

Protocol portability is not empirical portability. This project has not completed external-dataset validation. Step 3 pooling, Step 4 branch-mechanism, and Step 6 speaker-generalization No-Go decisions remain part of the evidence ledger rather than being silently removed. Step 5's S05 results remain specific to the frozen MELD artifact and do not transfer to another corpus.
"""


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate/finalize IEEE revision Step 7 protocol artifacts")
    parser.add_argument("--latex-log", type=Path)
    parser.add_argument("--visual-review-pass", action="store_true")
    parser.add_argument("--finalize", action="store_true")
    args = parser.parse_args()
    if args.finalize and (args.latex_log is None or not args.visual_review_pass):
        raise ValueError("--finalize requires --latex-log and --visual-review-pass")

    OUT.mkdir(parents=True, exist_ok=True)
    algorithm = algorithm_text()
    migration = migration_text()
    canonical = OUT / "algorithm_source.tex"
    migration_path = OUT / "migration_boundary.md"
    write_if_changed(canonical, algorithm)
    write_if_changed(PAPER_COPY, algorithm)
    write_if_changed(migration_path, migration)

    evidence_map = [
        {
            "algorithm_step": 1,
            "purpose": "define experimental object",
            "evidence": [
                "outputs/ieee_revision/step0_inventory/inventory.json",
                "outputs/ieee_revision/step3_pooling/preflight_contract.json",
                "supplementary/reproducibility/frozen_arrays.csv",
            ],
        },
        {
            "algorithm_step": 2,
            "purpose": "separate inherited backbone, audited factor, and training intervention",
            "evidence": [
                "paper/submission/source/main.tex#Method",
                "outputs/ieee_revision/step3_pooling/gate.json",
                "outputs/ieee_revision/step4_jsdg/gate.json",
                "outputs/ieee_revision/step6_spm/gate.json",
            ],
        },
        {
            "algorithm_step": 3,
            "purpose": "predeclare factors, contrasts, seeds, selection, and claim gates",
            "evidence": [
                "outputs/ieee_revision/step2_seeds/protocol.md",
                "outputs/ieee_revision/step2_seeds/seed_map.csv",
                "outputs/ieee_revision/step5_s05/filter_protocol.md",
            ],
        },
        {
            "algorithm_step": "4-6",
            "purpose": "train/dev-only selection and frozen test",
            "evidence": [
                "outputs/ieee_revision/step2_seeds/gate.json",
                "server_results/ieee_revision/step2_seeds/dev_selection_gate.json",
                "outputs/ieee_revision/step5_s05/gate.json",
                "server_results/ieee_revision/step5_s05/result_gate.json",
            ],
        },
        {
            "algorithm_step": 7,
            "purpose": "immutable paired-prediction join",
            "evidence": [
                "server_results/ieee_revision/step2_seeds/test_predictions.csv",
                "server_results/ieee_revision/step5_s05/test_predictions.csv",
                "outputs/ieee_revision/step4_jsdg/diagnostic_manifest.json",
            ],
        },
        {
            "algorithm_step": 8,
            "purpose": "separate task, robustness, utterance, and training-seed evidence",
            "evidence": [
                "outputs/ieee_revision/step2_seeds/local_audit.json",
                "outputs/ieee_revision/step4_jsdg/diagnostic_report.md",
                "outputs/ieee_revision/step5_s05/results_report.md",
            ],
        },
        {
            "algorithm_step": 9,
            "purpose": "hash artifacts and record environment",
            "evidence": [
                "server_results/ieee_revision/step2_seeds/final_manifest.json",
                "server_results/ieee_revision/step5_s05/final_manifest.json",
                "server_results/ieee_revision/step2_seeds/runtime/",
                "server_results/ieee_revision/step5_s05/runtime/",
            ],
        },
        {
            "algorithm_step": 10,
            "purpose": "claim ledger and No-Go handling",
            "evidence": [
                "outputs/ieee_revision/step3_pooling/gate.json",
                "outputs/ieee_revision/step4_jsdg/gate.json",
                "outputs/ieee_revision/step5_s05/gate.json",
                "outputs/ieee_revision/step6_spm/gate.json",
                "paper/submission/source/main.tex#Claim-Level-Gate-Outcomes",
            ],
        },
    ]

    inherited = {}
    for step in ("step3_pooling", "step4_jsdg", "step5_s05", "step6_spm"):
        for name in ("gate.json", "handoff.md"):
            path = ROOT / f"outputs/ieee_revision/{step}/{name}"
            inherited[str(path.relative_to(ROOT))] = sha256(path)

    gate = {
        "step": 7,
        "status": "prepared",
        "decision": "PASS_PROTOCOL_ALGORITHM_AND_MIGRATION_BOUNDARY_PREPARED",
        "server_used": False,
        "gpu_used": False,
        "new_training": False,
        "new_test_inference": False,
        "external_dataset_validation_completed": False,
        "algorithm": {
            "caption": "Frozen-Evidence Factorial Audit Protocol",
            "expected_number": 1,
            "main_manuscript_location": "Experimental Protocol, after Factorial Design and Candidate Freezing and before Matched Statistical Attribution",
            "canonical_path": str(canonical.relative_to(ROOT)),
            "paper_copy_path": str(PAPER_COPY.relative_to(ROOT)),
            "canonical_sha256": sha256(canonical),
            "paper_copy_sha256": sha256(PAPER_COPY),
            "copies_byte_equal": canonical.read_bytes() == PAPER_COPY.read_bytes(),
        },
        "evidence_map": evidence_map,
        "migration": {
            "path": str(migration_path.relative_to(ROOT)),
            "sha256": sha256(migration_path),
            "transferable": [
                "experimental-object definition process",
                "factor/contrast/seed preregistration",
                "train-dev selection and frozen-test separation",
                "immutable-ID pairing",
                "separate uncertainty layers",
                "artifact hashing and environment capture",
                "claim ledger",
            ],
            "not_transferable": [
                "MELD performance values or effect sizes",
                "MELD class labels and thresholds",
                "MELD split or speaker-overlap assumptions",
                "text-video-only factor set",
                "frozen-feature compute and randomness contract",
            ],
        },
        "inherited_gate_handoff_hashes": inherited,
        "generator": {
            "path": "scripts/build_revision_step7_protocol.py",
            "sha256": sha256(Path(__file__)),
        },
        "claim_boundary": "the protocol may transfer after redefining the experimental object; no performance conclusion is claimed to have transferred",
        "paper_edited": False,
        "latex_compile": "pending",
    }
    acceptance_text = ""
    if args.finalize:
        log_path = args.latex_log if args.latex_log.is_absolute() else ROOT / args.latex_log
        log_text = log_path.read_text(encoding="utf-8", errors="replace")
        undefined = len(re.findall(r"undefined (?:references|citations)|Citation .* undefined|Reference .* undefined", log_text, flags=re.I))
        errors = len(re.findall(r"^! ", log_text, flags=re.M))
        page_matches = re.findall(r"Output written on main\.pdf \((\d+) pages", log_text)
        if errors or undefined or not page_matches:
            raise ValueError(f"LaTeX acceptance failed: errors={errors} undefined={undefined} pages={page_matches}")
        manuscript = ROOT / "paper/submission/source/main.tex"
        pdf = ROOT / "paper/submission/source/main.pdf"
        if not pdf.is_file():
            raise FileNotFoundError(pdf)
        gate.update({
            "status": "complete",
            "decision": "PASS_STEP7_PROTOCOL_ALGORITHM_AND_MIGRATION_BOUNDARY",
            "paper_edited": True,
            "latex_compile": "PASS",
            "latex_pages": int(page_matches[-1]),
            "latex_errors": errors,
            "undefined_references_or_citations": undefined,
            "overfull_hbox_warnings": len(re.findall(r"Overfull \\hbox", log_text)),
            "visual_review": "PASS_ALGORITHM_AND_MIGRATION_PAGES",
            "visual_review_pages": [6, 9, 10],
            "manuscript": {"path": str(manuscript.relative_to(ROOT)), "sha256": sha256(manuscript)},
            "pdf": {"path": str(pdf.relative_to(ROOT)), "sha256": sha256(pdf)},
        })
        acceptance_text = f"""
## Manuscript acceptance

The final manuscript places Algorithm 1 in the Experimental Protocol source between the factorial-design and matched-statistics subsections. It compiles to {gate['latex_pages']} pages with zero LaTeX errors and zero undefined references/citations. Visual review of pages 6, 9, and 10 confirms that the two-column algorithm, migration discussion, and claim ledger are readable and unclipped. The log retains {gate['overfull_hbox_warnings']} IEEE Access class/title output warnings.

- `paper/submission/source/main.tex` — `{gate['manuscript']['sha256']}`
- `paper/submission/source/main.pdf` — `{gate['pdf']['sha256']}`
"""
    write_json(OUT / "gate.json", gate)

    mapping_lines = []
    for row in evidence_map:
        paths = "; ".join(f"`{path}`" for path in row["evidence"])
        mapping_lines.append(f"- Algorithm line {row['algorithm_step']} ({row['purpose']}): {paths}")
    handoff = f"""# IEEE Access revision Step 7 handoff

## Algorithm placement

Algorithm 1, **Frozen-Evidence Factorial Audit Protocol**, is placed in the main manuscript's Experimental Protocol section, after `Factorial Design and Candidate Freezing` and before `Matched Statistical Attribution`. The canonical revision source is `outputs/ieee_revision/step7_protocol/algorithm_source.tex`; the byte-identical self-contained submission copy is `paper/submission/source/generated/frozen_evidence_factorial_audit_algorithm.tex`.

## Algorithm-to-evidence map

{chr(10).join(mapping_lines)}

## Migration boundary

Transferable items are the protocol operations: object definition, factor and contrast preregistration, train/dev selection with frozen test, immutable-ID pairing, separation of uncertainty layers, hashing/environment capture, and the claim ledger.

Non-transferable items are MELD scores and effect sizes, labels and thresholds, split/speaker assumptions, the text-video-only factor set, and the frozen-feature compute/randomness contract. IEMOCAP requires session/speaker-independent folds; CMU-MOSEI requires new task-unit, label, modality, alignment, and sequence contracts; trimodal tasks require audio availability and interactions; end-to-end training requires a new compute, nondeterminism, and artifact contract.

Protocol portability is not performance portability. No external dataset validation was run, and no manuscript sentence may imply otherwise.

## Inherited Step 3--6 decisions

- Step 3: pooling experiment `No-Go`; Last-Token remains inherited, not optimal.
- Step 4: bounded frozen diagnostic; branch-logit and causal-mechanism claims remain `No-Go`.
- Step 5: completed eight-seed S05 comparison; wording remains artifact-specific and quality-constrained.
- Step 6: speaker-held-out training `No-Go`; SPM remains dataset-specific.

{acceptance_text}

## Reproduction

```bash
python3 -m py_compile scripts/build_revision_step7_protocol.py
python3 scripts/build_revision_step7_protocol.py
cd paper/submission/source
latexmk -pdf -interaction=nonstopmode -halt-on-error main.tex
cd ../../..
python3 scripts/build_revision_step7_protocol.py --latex-log paper/submission/source/main.log --visual-review-pass --finalize
```
"""
    write_if_changed(OUT / "handoff.md", handoff)
    print(json.dumps({
        "decision": gate["decision"],
        "algorithm_sha256": gate["algorithm"]["canonical_sha256"],
        "copies_byte_equal": gate["algorithm"]["copies_byte_equal"],
        "external_validation": gate["external_dataset_validation_completed"],
    }, indent=2))


if __name__ == "__main__":
    main()
